"""adiciona campo 'item' ao model de pedido

Revision ID: 4251a02f25ee
Revises: 99b0e7ec447e
Create Date: 2026-02-06 16:30:33.820933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4251a02f25ee'
down_revision: Union[str, Sequence[str], None] = '99b0e7ec447e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
